FROM ruby:2.4-alpine3.7
#RUN apt-get update -qq && apt-get install -y build-essential
#RUN apk --update add build-base

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN apk update --no-cache \
 && apk add --no-cache build-base \
 && gem install bundler -v 2.3.26 \
 && rm -rf /var/cache/apk/*
#RUN bundle install
ADD . $APP_HOME

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

CMD ["puma"]
